#!/bin/bash 
#Простой запрос к ластику 

curl -XGET 'http://10.206.148.120:9200/msr_vk/_search?pretty' -H 'Content-Type: application/json' -d '{
"query" : {
"term" : {
"data.id" : "aa74c72a576d718800e551b04745bbbe"
   }
  }
}'
