#!/bin/bash 
#Простой запрос к ластику 

curl -XGET 'http://10.206.148.120:9200/msr_vk/_search?pretty' -H 'Content-Type: application/json' -d '{
"query" : {
"term" : {
"data.snils" : "12966373395"
   }
  }
}'
